 # AutoDisputer configuration file
feeds: # please reference https://github.com/tellor-io/dataSpecs/tree/main/types for examples of QueryTypes w/ Query Parameters
#ETH/USD
  - query_id: "0x83a7f3d48786ac2667503a61e8c415438ed2922eb86a2906e4ee66d9a2ce4992"
    threshold:
      type: Percentage
      amount: 0.75 # 75%
#BTC/USD
  - query_id: "0xa6f013ee236804827b77696d350e9f0ac3e879328f2a3021d473a0b778ad78ac"
    threshold:
      type: Percentage
      amount: 0.75 # 75%
#OP/USD
  - query_id: "0xafc6a3f6c18df31f1078cf038745b48e55623330715d90efe3dc7935efd44938"
    threshold:
      type: Percentage
      amount: 0.75 # 75%
#STETH/USD
  - query_id: "0x907154958baee4fb0ce2bbe50728141ac76eb2dc1731b3d40f0890746dd07e62"
    threshold:
      type: Percentage
      amount: 0.75 # 75%
#TRB/USD
  - query_id: "0x5c13cd9c97dbb98f2429c101a2a8150e6c7a0ddaff6124ee176a3a411067ded0"
    threshold:
      type: Percentage
      amount: 0.75 # 75%
  - query_type: EVMCall
    threshold:
      type: Equality
