[tool.poetry]
name = "tellor-disputables"
version = "0.0.1"
description = "dashboard & text alerts for disputable values reported to Tellor oracles"
authors = ["oraclown <oburton@tellor.io>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.10.2"
streamlit = "^1.7.0"
twilio = "^7.7.0"
web3 = "^5.28.0"
telliot-core = "^0.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
data = "tellor_disputables.data:main"