[tool.poetry]
name = "tellor-disputables"
version = "0.0.1"
description = "dashboard & text alerts for disputable values reported to Tellor oracles"
authors = ["oraclown <info@tellor.io>"]
license = "MIT"
packages = [{ include = "tellor_disputables", from = "src" }]

[tool.poetry.dependencies]
python = "^3.10.2"
twilio = "^7.7.0"
web3 = "5.27.0"
pandas = "^1.4.1"
tabulate = "^0.8.9"
pytest-asyncio = "^0.19.0"
telliot-core = {git = "https://github.com/tellor-io/telliot-core.git", rev = "main"}
telliot-feeds = {git = "https://github.com/tellor-io/telliot-feeds.git", rev = "main"}

[tool.poetry.dev-dependencies]
pytest = "^7.1.0"
black = "^22.1.0"
pre-commit = "^2.17.0"
mypy = "^0.942"
types-python-dateutil = "^2.8.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
cli = "tellor_disputables.cli:main"
data = "tellor_disputables.data:main"

[tool.pytest.ini_options]
pythonpath = ["src"]
