# Per:
# https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

name: Publish

on:
  release:
    types: [published, released]

jobs:
  build-n-publish:
    name: Publish tellor-disputables
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@dvm-main
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Publish tellor-disputables to Test PyPI
      if: "github.event.release.prerelease"
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TELLOR_DISPUTABES_TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish tellor-disputables to PyPI
      if: "!github.event.release.prerelease"
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TELLOR_DISPUTABES_PYPI_API_TOKEN }}